config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get "home/about" => 'homes#about', as:'about'
  resources :books do
   resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
   belongs_to :user
   has_many :book_comments, dependent: :destroy
   has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  validates :body,    length: { maximum: 200 } 
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    validates :comment, presence: true
   belongs_to :book
   belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
   validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
        
  
  has_many :books, dependent: :destroy
  attachment :profile_image
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  

  validates :name, presence: true
  
  validates :name,    length: { minimum: 2 } 
  validates :name,    length: { maximum: 20 } 
  validates :name, uniqueness: true
  validates :introduction,    length: { maximum: 50} 
  # validates :introduction
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  def after_sign_in_path_for(resource)
    user_path(resource) # ログイン後に遷移するpathを設定
  end

  def after_sign_out_path_for(resource)
    root_path # ログアウト後に遷移するpathを設定
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

    def destroy
      BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
      redirect_to book_path(params[:book_id])
    end
    
   private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!
  before_action :baria_user, only: [:edit, :destroy, :update]


 def show
    @book = Book.find(params[:id])
    @newbook = Book.new
    @user = @book.user
    @book_comment = BookComment.new


 end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user



  end

  def create
        @book = Book.new(book_params)
        @book.user_id = current_user.id
      if @book.save


          redirect_to book_path(@book.id), notice: 'Book was successfully created.'
      else
          @books = Book.all
          @user = current_user
          render :index
      end
  end



  def top

  end



  def edit
     @book = Book.find(params[:id])
  end
  
  def comments
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    if @book.save
       redirect_to book_path(@book), notice: 'You have updated book successfully.'
    else
      render :edit
    end

    # redirect_to book_path(@book.id)
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path, notice: 'Book was successfully destroyed.'
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def baria_user
    unless Book.find(params[:id]).user.id.to_i == current_user.id
        redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to  request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end

  def index
    @book = books.all
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  
  def new
    @post_image = PostImage.new  
  end
  
　 def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    @post_image.save
    redirect_to book_path  
  end
  
   private

  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

 def show
    @users = User.all
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books.all

 end

  def index
    @users = User.all
    @book = Book.new
    @user = current_user

  end

  def create
        @book = Book.new(book_params)
        @user = User.new(user_params)
      if @book.save

          redirect_to book_path(@book.id), notice: 'Book was successfully created.'
      else
          @books = Book.all
          render :index
      end

      if @user.save

          redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
      else
          @users = user.all
          render :index
      end
  end



  def top

  end



  def edit
     @user = User.find(params[:id])
     if @user != current_user
       redirect_to user_path(current_user)
     end

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_path(@user), notice: 'You have updated user successfully.'
    else
      render :edit
    end


  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path, notice: 'Book was successfully destroyed.'
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/user　inedx_helper.rb
module User　inedxHelper
end

app/views/books/edit.html.erb
<body>


<h1>Editing Book</h1>
<%= form_with model:@book, local: true do |f| %>
 <% if @book.errors.any? %>
      <%= @book.errors.count %>件のerror
      <% @book.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
  <% end %>

      <div class="field">
        <label for="book_title">Title</label>
        <%= f.text_field :title %>
      </div>

      <div class="field">
        <label for="book_body">Body</label>
        <%= f.text_area :body %>
      </div>
      
      <div class="actions">
         <%= f.submit 'Update Book' %>
      </div>
    </form>

     <%= link_to "Show", book_path(@book) %>
     <%= link_to "Back", href="/books" %>

<% end %>


</body>

app/views/books/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body> -
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <main>
          <p id="notice"></p>
          <h1>Users info</h1><img class="attachment user profile_image fallback" src="/assets/no_image-ede28af4bad96368ef41be1b4be1cffce0d9402540f75d17895e32cb0d2af5e6.jpg">
          <table>
            <tr></tr>
            <thead>
              <tr>
                <th>name</th>
                <th>introduction</th>
              </tr>
            </thead>
            <tbody>
              <%= link_to edit_user_path(@user) ,class: "btn btn-block btn-outline-secondary", type: "button" do %>
              <span aria-hidden="true" class="fas fa-user-cog"></span>
                <%end %>
                  <tr>
                    <td>
                      <%= @user.name %>
                    </td>
                    <td>
                      <%= @user.introduction %>
                    </td>
                  </tr>
            </tbody>
          </table>
          <div class="row"></div>
          <h2 class="mt-3">New book</h2>
          <form accept-charset="UTF-8" action="/books" method="post"> <input name="utf8" type="hidden" value="✓"> <input name="authenticity_token" type="hidden" value="9DnKTmGqMpxtNiuIUH8t9bbrwkGKjDxaEh2lAPXX7MvpGCYXouPLnO3hMGXwqv1EStmMtSidkJ79zlcrm87d9w==">
            <div class="form-group">
              <%= form_with model: @book,url: books_path, local:true do |f| %>
                <%if @book.errors.any? %>
                  <%= @book.errors.count %>件のerror
                    <%@book.errors.full_messages.each do |message| %>
                      <%= message %>
                        <%end %>
                          <%end %>
                            <h4>Title</h4>
                            <%= f.text_field :title %>
                              <h4>Opinion</h4>
                              <%= f.text_field :body %>
                                <%= f.submit 'Create Book' %>
                                  <%end %>
            </div>

          </form>
        </main>
      </div>
      <div class="col-md-8 offset-md-1">
        <h1>Books</h1>
        <table>
          <caption>
            <table>
              <thead>
                <tr>
                  <th>Title</th>
                  <th>Body</th>
                </tr>
              </thead>
              <tbody>
                <%@books.each do |book| %>
                  <tr>
                    <td>
                      <%= link_to user_path(book.user) do %>
                        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
                          <%end %>
                    </td>
                    <td>
                      <%= link_to book.title, book_path(book) %>
                    </td>
                    <td>
                      <%= book.body %>
                    </td>
            			<td>
            				<div class="comments">
            					<p>コメント件数： <%= book.book_comments.count %></p>
            				</div>
            			</td>
            			<td>
            				<%if book.favorited_by?(current_user) %>
            				<p><%= link_to book_favorites_path(book), method: :delete do %>  <span class="fas fa-heart" aria-hidden="true" 　fa-100x></span><%= book.favorites.count %> いいね <%end %></p><%else %>
            				<p><%= link_to book_favorites_path(book), method: :post do %>  <span class="far fa-heart" aria-hidden="true" 　fa-100x></span><%= book.favorites.count %> いいね <%end %></p><%end %>
            			</td>
                  </tr>
                  <%end %>
              </tbody>
            </table>
          </caption>
        </table>
         <footer>
          <div class="container mt-5">
            <div class="row">
              <div class="mx-auto">
                <p>CopyRight Infratop.inc</p>
              </div>
            </div>
          </div>
        </footer>
      </div>
    </div>
  </div>
</body>
</html>

app/views/books/show.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <main>
          <p id=“notice”>
            <%= notice %>
          </p>
          <table>
            <h1>Users info
              <h1> <img class="attachment user profile_image fallback" src="/assets/no_image-ede28af4bad96368ef41be1b4be1cffce0d9402540f75d17895e32cb0d2af5e6.jpg">
                <table class="table">
                  <thead>
                    <tr>
                      <th>name</th>
                      <th>introduction</th>
                    </tr>
                  </thead>
                  <tbody>
                    <%= link_to edit_user_path(@user),class: "btn btn-block btn-outline-secondary", type: "button" do %> <span class="fas fa-user-cog" aria-hidden="true" 　fa-100x></span>
                      <% end %>
                        <tr>
                          <td>
                            <%= @user.name %>
                          </td>
                          <td>
                            <%= @user.introduction %>
                          </td>
                        </tr>
                  </tbody>
                </table>
                <div class="row"> </div>
                <h2>New book</h2>
                <form action="/books" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="9DnKTmGqMpxtNiuIUH8t9bbrwkGKjDxaEh2lAPXX7MvpGCYXouPLnO3hMGXwqv1EStmMtSidkJ79zlcrm87d9w==">
                  <div class="form-group">
                    <%= form_with model: @newbook,url: books_path, local:true do |f| %>
                      <% if @newbook.errors.any? %>
                        <%= @newbook.errors.count %>件のerror
                          <% @newbook.errors.full_messages.each do |message| %>
                            <%= message %>
                              <% end %>
                                <% end %>
                                  <h4>Title</h4>
                                  <%= f.text_field :title %>
                                    <h4></h4>
                                    <%= f.text_field :body %>
                                      <%= f.submit 'Create Book' %>
                                        <% end %>
                </form>
                </div>
      </div>
      <div class="col-md-8 offset-md-1">
        <table>
          <h1>Book detail
            <caption>
              <tbody>
                <tr>
                  <td>
                    <%= link_to user_path(@user) do %>
                      <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
                        <% end %>
                  </td>
                  <td>
                    <%= link_to @book.title, book_path %>
                  </td>
                  <td>
                    <%= @book.body %>
                  </td>
                  <td>
                    <p>
                      <% if @book.favorited_by?(current_user) %>
                        <%= link_to book_favorites_path(@book), method: :delete do %> <span class="fas fa-heart" aria-hidden="true" 　fa-100x></span>
                          <%= @book.favorites.count %> いいね
                            <% end %>
                    </p>
                    <% else %>
                      <p>
                        <%= link_to book_favorites_path(@book), method: :post do %> <span class="far fa-heart" aria-hidden="true" 　fa-100x></span>
                          <%= @book.favorites.count %> いいね
                            <% end %>
                      </p>
                      <% end %>
                  </td>
                  <td>
                    <p>コメント件数：
                      <%= @book.book_comments.count %>
                    </p>
                  </td>
                </tr>
                <tr>
                  <td>
                    <% if @user.id == current_user.id %>
                      <%= link_to "Edit", edit_book_path(@book) %>
                        <%= link_to "Destroy", book_path(@book), method: :delete %>
                          <% end %>
                            <%= link_to @user.name, user_path(@user) %>
                  </td>
                </tr>
              </tbody>
        </table>
        <table>
          <div class="comments">
            <% @book.book_comments.each do |book_comment| %>
              <tr>
                <td>
                  <%= link_to user_path(@user) do %>
                    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
                      <% end %>
                </td>
                <td>
                  <%= book_comment.comment %>
                </td>
                <td>
                  <% if book_comment.user == current_user %>
                    <div class="comment-delete">
                      <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger", type: "button" %>
                    </div>
                    <% end %>
                </td>
              </tr>
              <tr>
                <td>
                  <%=link_to book_comment.user.name, @user %>
                </td>
              </tr>
              <% end %>
          </div>
        </table>
        <div class="new-comment">
          <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
            <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
              <%= f.submit "送信する" %>
                <% if @book_comment.user == current_user %>
                  <div class="comment-delete">
                    <%= link_to "削除", book_book_comment_path(book_comment.book, book_comment), method: :delete %>
                  </div>
                  <% end %>
                    <% end %>
        </div>
      </div>
      </main>
      <footer>
        <div class="container mt-5">
          <div class="row">
            <div class="mx-auto">
              <p>CopyRight Infratop.inc</p>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </div>
  </div>
  </div>
</body>

app/views/homes/about.html.erb
<h1>Welcome to Bookers!</h1>
<p>CopyRight Infratop.inc</p>

<i class="fas fa-book"></i>

app/views/homes/index.html.erb
<body>
    <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <li><a class="fas fa-home nav-link text-light" href="/users/23764"> Home</a></li>
          <li><a class="fas fa-users nav-link text-light" href="/users"> Users</a></li>
          <li><a class="fas fa-book-open nav-link text-light" href="/books"> Books</a></li>
          <li><a class="fas fa-sign-out-alt nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out"> logout</a></li>
        </ul>
      </div>
    </div>
  </nav>
</header>
      <main>
        <p id="notice">Welcome! You have signed up successfully.</p>
        <div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <img class="attachment user profile_image fallback" src="/assets/no_image-ede28af4bad96368ef41be1b4be1cffce0d9402540f75d17895e32cb0d2af5e6.jpg"><table class="table">
  <tbody><tr></tr>
  <tr>
	  <th>name</th>
	  <th>小枝慎太郎</th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th></th>
  </tr>
</tbody></table>
　
<div class="row">
  <a class="btn btn-outline-secondary btn-block fas fa-user-cog edit_user_23764" href="/users/23764/edit"></a>
</div>
      <h2 class="mt-3">New book</h2>
      <form action="/books" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="nd/r/Bcq6V9K1MF0ZYGHXG2Q+RqZrPdZARfM2VNy6CWA/gel1GMQX8oD2pnFVFftkaK37ju9W53uxD7yPWvZGQ==">
  <div class="form-group">
    <label for="book_title">Title</label>
    <input class="form-control book_title" type="text" name="book[title]" id="book_title">
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <textarea class="form-control book_body" name="book[body]" id="book_body"></textarea>
  </div>
  <div class="form-group">
    <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
  </div>
</form>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>
    </div>
  </div>
</div>
      </main>
    <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

  

</body>

app/views/homes/top.html.erb
</header>
      <main>
        <p id="notice">Signed out successfully.</p>
        <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
</div>


      </main>
    <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

  

</body>

app/views/users/edit.html.erb
<body>
    <h1>User info</h1>
      <%= form_with model:@user, local: true  do |f| %>
       <% if @user.errors.any? %>
            <%= @user.errors.count %>件のerror
            <% @user.errors.full_messages.each do |message| %>
              <%= message %>
            <% end %>
        <% end %>

      <div class="field">
        <label for="book_title">Name</label>
        <%= f.text_field :name %>
      </div>
      
      <div class="field">
        <label for="book_image">Image</label>
        <%= f.attachment_field :profile_image %>
      </div>
      

      <div class="field">
        <label for="book_body">Introduction</label>
        <%= f.text_area :introduction %>
      </div>

      <div class="actions">

         <%= f.submit 'Update User' %>
      </div>
    </form>



<% end %>

    <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>



</body>

app/views/users/index.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <table>
        <h1>Users info
          <h1> <img class="attachment user profile_image fallback" src="/assets/no_image-ede28af4bad96368ef41be1b4be1cffce0d9402540f75d17895e32cb0d2af5e6.jpg">
            <table class="table">
              <thead>
                <tr>
                  <th>name</th>
                  <th>introduction</th>
                </tr>
              </thead>
              <tbody>
                <%= link_to edit_user_path(@user),class: "btn btn-block btn-outline-secondary", type: "button" do %> <span class="fas fa-user-cog" aria-hidden="true" 　fa-100x></span>
                  <% end %>
                    <tr>
                      <td>
                        <%= @user.name %>
                      </td>
                      <td>
                        <%= @user.introduction %>
                      </td>
                    </tr>
              </tbody>
            </table>
            <h1>New book</h1>
            <%= form_with model: @book,url: books_path, local:true do |f| %>
              <% if @book.errors.any? %>
                <%= @book.errors.count %>件のerror
                  <% @book.errors.full_messages.each do |message| %>
                    <%= message %>
                      <% end %>
                        <% end %>
                          <h4>Title</h4>
                          <%= f.text_field :title %>
                            <h4>Opinion</h4>
                            <%= f.text_field :body %>
                              <%= f.submit 'Create Book' %>
                                <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <table>
        <h1>User
          <h1>
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td>
                    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
                  </td>
                  <td>
                    <%= user.name %>
                  </td>
                  <td>
                    <%= link_to "Show", user_path(user) %>
                  </td>
                </tr>
                <% end %>
            </tbody>
      </table>

    </div>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </div>
</div>

app/views/users/show.html.erb
<p id=“notice”>
  <%= notice %>
</p>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <table>
        <h1>Users info
          <h1>
            <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
              <thead>
                <tr>
                  <th>name</th>
                  <th>introduction</th>
                </tr>
              </thead>
              <tbody>
                <%= link_to edit_user_path(@user),class: "btn btn-block btn-outline-secondary", type: "button" do %>
                  <span class="fas fa-user-cog" aria-hidden="true" 　fa-100x></span>
                  <% end %>
                    <tr>
                      <td>
                        <%= @user.name %>
                      </td>
                      <td>
                        <%= @user.introduction %>
                      </td>
                    </tr>
              </tbody>
      </table>
      <h1>New book</h1>
      <%= form_with model: @book,url: books_path, local:true do |f| %>
        <% if @book.errors.any? %>
          <%= @book.errors.count %>件のerror
            <% @book.errors.full_messages.each do |message| %>
              <%= message %>
                <% end %>
                  <% end %>
                    <h4>Title</h4>
                    <%= f.text_field :title %>
                      <h4>Opinion</h4>
                      <%= f.text_field :body %>
                        <%= f.submit 'Create Book' %>
                          <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <table>
        <h1>Books
          <h1>
            <thead>
              <tr>
                <th>Title</th>
                <th>Opinion</th>
              </tr>
            </thead>
            <tbody>
              </thead>
              <tbody>

                <%@books.each do |book| %>
                  <tr>
                    <td>
                      <%= link_to user_path(book.user) do %>
                        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
                          <%end %>
                    </td>
                    <td>
                      <%= link_to book.title, book_path(book) %>
                    </td>
                    <td>
                      <%= book.body %>
                    </td>
                    <td>
                      <div class="comments">
                        <p>コメント件数：
                          <%= book.book_comments.count %>
                        </p>
                      </div>
                    </td>
                    <td>
                      <%if book.favorited_by?(current_user) %>
                        <p>
                          <%= link_to book_favorites_path(book), method: :delete do %> <span class="fas fa-heart" aria-hidden="true" 　fa-100x></span>
                            <%= book.favorites.count %> いいね
                              <%end %>
                        </p>
                        <%else %>
                          <p>
                            <%= link_to book_favorites_path(book), method: :post do %> <span class="far fa-heart" aria-hidden="true" 　fa-100x></span>
                              <%= book.favorites.count %> いいね
                                <%end %>
                          </p>
                          <%end %>
                    </td>
                  </tr>
                  <%end %>
              </tbody>
      </table>
    </div>
    <footer>
      <p>CopyRight Infratop.inc</p>
    </footer>
  </div>
</div>